### PR TITLE
Rebase resources at constants and Use Constants vars

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by jjskuld** [comment]
@Furtif Can you commit the missing file?

**Comment by Furtif** [comment]
@jjskuld unused  file resources after merge

**Comment by Furtif** [comment]
Content resources.cs deplace in constants.cs

**Comment by jjskuld** [comment]
I see.. OK then we need to remove the resources.cs from the csproj to fix the build. Currently Appveyor build is failing.

**Comment by Furtif** [comment]
Yes it's for her that gives error

**Comment by jjskuld** [comment]
@Furtif Can you make the change to the csproj so that we can get the build to succeed? Then I can merge.

**Comment by Furtif** [comment]
Ok no worries, it's done

**Pull request merged**
